# Generated by Django 4.0.5 on 2022-06-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'characteristic',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cost', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('MODERATION', 'Moderation'), ('AVAILABLE', 'Available'), ('SOLD_OUT', 'Sold Out'), ('ON_HOLD', 'On Hold'), ('DELETED', 'Deleted')], default='AVAILABLE', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.category', verbose_name='category_id')),
                ('characteristic', models.ManyToManyField(db_table='links_product_to_characteristic', related_name='+', to='stock.characteristic')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
